### ISSUE TITLE
win11双击没反应呢

### ISSUE THREAD

**Issue by DYJason369** [lawnvi/whisper#2]
win11系统，安装完毕后双击快捷方式没反应，打不开~

**Comment by lawnvi** [comment]
> win11系统，安装完毕后双击快捷方式没反应，打不开~

试试[dev-v0.0.15](https://github.com/lawnvi/whisper/releases/download/dev-v0.0.15/whisper-windows-x86_64.exe)吧，可能引入了什么问题，我晚上看看~

**Comment by lawnvi** [comment]
> > win11系统，安装完毕后双击快捷方式没反应，打不开~
> 
> 试试[dev-v0.0.15](https://github.com/lawnvi/whisper/releases/download/dev-v0.0.15/whisper-windows-x86_64.exe)吧，可能引入了什么问题，我晚上看看~

应该可以了[dev-v0.0.17](https://github.com/lawnvi/whisper/releases/download/dev-v0.0.17/whisper-windows-x86_64.exe)

**Comment by DYJason369** [comment]
好来大佬，今儿试一下





------------------ 原始邮件 ------------------
发件人: lawnvi ***@***.***&gt;
发送时间: 2024年6月28日 23:23
收件人: lawnvi/whisper ***@***.***&gt;
抄送: DYJason369 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [lawnvi/whisper] win11双击没反应呢 (Issue #2)





   
win11系统，安装完毕后双击快捷方式没反应，打不开~
  
试试dev-v0.0.15吧，可能引入了什么问题，我晚上看看~
  
应该可以了dev-v0.0.17

**Comment by DYJason369** [comment]
Win11 系统，打开报错。小米澎湃系统，也是报错。





------------------ 原始邮件 ------------------
发件人: lawnvi ***@***.***&gt;
发送时间: 2024年6月28日 23:23
收件人: lawnvi/whisper ***@***.***&gt;
抄送: DYJason369 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [lawnvi/whisper] win11双击没反应呢 (Issue #2)





   
win11系统，安装完毕后双击快捷方式没反应，打不开~
  
试试dev-v0.0.15吧，可能引入了什么问题，我晚上看看~
  
应该可以了dev-v0.0.17

**Comment by lawnvi** [comment]
> Win11 系统，打开报错。小米澎湃系统，也是报错。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: lawnvi ***@***.***&gt; 发送时间: 2024年6月28日 23:23 收件人: lawnvi/whisper ***@***.***&gt; 抄送: DYJason369 ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [lawnvi/whisper] win11双击没反应呢 (Issue #2) win11系统，安装完毕后双击快捷方式没反应，打不开~ 试试dev-v0.0.15吧，可能引入了什么问题，我晚上看看~ 应该可以了dev-v0.0.17 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可以描述一下操作，发一下对应的报错截图吗

**Comment by DYJason369** [comment]
------------------ 原始邮件 ------------------
发件人: lawnvi ***@***.***&gt;
发送时间: 2024年6月29日 19:47
收件人: lawnvi/whisper ***@***.***&gt;
抄送: DYJason369 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [lawnvi/whisper] win11双击没反应呢 (Issue #2)





  
Win11 系统，打开报错。小米澎湃系统，也是报错。
 …
 ------------------ 原始邮件 ------------------ 发件人: lawnvi @.&gt; 发送时间: 2024年6月28日 23:23 收件人: lawnvi/whisper @.&gt; 抄送: DYJason369 @.&gt;, Author @.&gt; 主题: Re: [lawnvi/whisper] win11双击没反应呢 (Issue #2) win11系统，安装完毕后双击快捷方式没反应，打不开~ 试试dev-v0.0.15吧，可能引入了什么问题，我晚上看看~ 应该可以了dev-v0.0.17 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
可以描述一下操作，发一下对应的报错截图吗

**Comment by DYJason369** [comment]
附图了啊大佬





------------------ 原始邮件 ------------------
发件人: lawnvi ***@***.***&gt;
发送时间: 2024年6月29日 19:47
收件人: lawnvi/whisper ***@***.***&gt;
抄送: DYJason369 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [lawnvi/whisper] win11双击没反应呢 (Issue #2)





  
Win11 系统，打开报错。小米澎湃系统，也是报错。
 …
 ------------------ 原始邮件 ------------------ 发件人: lawnvi @.&gt; 发送时间: 2024年6月28日 23:23 收件人: lawnvi/whisper @.&gt; 抄送: DYJason369 @.&gt;, Author @.&gt; 主题: Re: [lawnvi/whisper] win11双击没反应呢 (Issue #2) win11系统，安装完毕后双击快捷方式没反应，打不开~ 试试dev-v0.0.15吧，可能引入了什么问题，我晚上看看~ 应该可以了dev-v0.0.17 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
可以描述一下操作，发一下对应的报错截图吗

**Comment by lawnvi** [comment]
![WeChatacb445051ffaee18d9a127010ce7c02d](https://github.com/lawnvi/whisper/assets/48850461/360d23b9-6d85-4347-86a1-6d16d4b1f1a7)
看不到额~ @DYJason369

**Comment by DYJason369** [comment]
Mr.Z
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lawnvi/whisper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月29日(星期六) 晚上8:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lawnvi/whisper] win11双击没反应呢 (Issue #2)





 
WeChatacb445051ffaee18d9a127010ce7c02d.jpg (view on web)
 看不到额~ @DYJason369

**Comment by lawnvi** [comment]
> Mr.Z ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lawnvi/whisper" ***@***.***&gt;; 发送时间:&nbsp;2024年6月29日(星期六) 晚上8:19 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [lawnvi/whisper] win11双击没反应呢 (Issue #2) WeChatacb445051ffaee18d9a127010ce7c02d.jpg (view on web) 看不到额~ @DYJason369 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

在这里[反馈](https://feedback.127014.xyz)一下吧，图片不要太大，临时的网速比较慢

**Comment by DYJason369** [comment]
图片能看到了吗大佬



------------------ 原始邮件 ------------------
发件人: lawnvi ***@***.***&gt;
发送时间: 2024年7月2日 20:53
收件人: lawnvi/whisper ***@***.***&gt;
抄送: DYJason369 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [lawnvi/whisper] win11双击没反应呢 (Issue #2)





  
Mr.Z @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lawnvi/whisper" @.&gt;; 发送时间:&nbsp;2024年6月29日(星期六) 晚上8:19 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [lawnvi/whisper] win11双击没反应呢 (Issue #2) WeChatacb445051ffaee18d9a127010ce7c02d.jpg (view on web) 看不到额~ @DYJason369 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
在这里反馈一下吧，图片不要太大，临时的网速比较慢

**Comment by lawnvi** [comment]
> 图片能看到了吗大佬
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: lawnvi ***@***.***&gt; 发送时间: 2024年7月2日 20:53 收件人: lawnvi/whisper ***@***.***&gt; 抄送: DYJason369 ***@***.***&gt;, Mention ***@***.***&gt; 主题: Re: [lawnvi/whisper] win11双击没反应呢 (Issue #2) Mr.Z @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lawnvi/whisper" @.&gt;; 发送时间:&nbsp;2024年6月29日(星期六) 晚上8:19 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [lawnvi/whisper] win11双击没反应呢 (Issue #2) WeChatacb445051ffaee18d9a127010ce7c02d.jpg (view on web) 看不到额~ @DYJason369 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt; 在这里反馈一下吧，图片不要太大，临时的网速比较慢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

看不到额，用这个上传一下截图和复现方法吧，就是有点慢 https://feedback.127014.xyz/
